### ISSUE TITLE
tests for logShout and logWhisper not working

### ISSUE THREAD

**Issue by HarlemSquirrel** [learn-co-students/javascript-intro-to-functions-lab-js-apply-000#2]
Students are reporting and I can verify that these tests are showing `Error: spy was never called with [ 'HELLO' ]` for both functions. 

output in terminal
```
> java-script-intro-to-functions-lab@0.1.0 test /home/hs/code/jw-garrison/javascript-intro-to-functions-lab-js-apply-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 5   -_-_-_-__,------,
 2   -_-_-_-__|  /\_/\ 
 0   -_-_-_-_~|_( x .x) 
     -_-_-_-_ ""  "" 

  5 passing (3s)
  2 failing

  1) logShout(string) calls console.log() its one argument in all caps:
     Error: spy was never called with [ 'HELLO' ]
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toHaveBeenCalledWith (node_modules/expect/lib/Expectation.js:333:28)
      at Context.<anonymous> (test/index-test.js:24:17)

  2) logWhisper(string) calls console.log() its one argument in all lowercase:
     Error: spy was never called with [ 'hello' ]
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toHaveBeenCalledWith (node_modules/expect/lib/Expectation.js:333:28)
      at Context.<anonymous> (test/index-test.js:36:17)
```

**Comment by constgoh** [comment]
Hi there, this is still happening. Please advise on what we should do. 
Thanks!

**Comment by ritchey0713** [comment]
any resolve to this?

**Comment by brendangraff23** [comment]
This error might be issued because string.toUpperCase() or string.toLowerCase() was missing parentheses at the end.

**Comment by RWJL** [comment]
> This error might be issued because string.toUpperCase() or string.toLowerCase() was missing parentheses at the end.
You hit the nail on the head!

**Comment by jpoze** [comment]
This happened to me, but the issue resolved when I fixed Logwhisper(String). I had erroneously put console.log(string.toLowerCase());  instead of console.log(string.toUpperCase());

The test wanted it to be whispered, and I had put it in caps. (Should have been toLowercase instead of toUppercase).

**Comment by gufu-j** [comment]
Thanks jpoze, that really helped me. Had same issue now that suggestion fixed!, thank you

**Comment by brooke-burris** [comment]
1) logShout(string)
       takes a string argument and logs it in all caps using console.log():
     Error: spy was never called with [ 'HELLO' ]
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toHaveBeenCalledWith (node_modules/expect/lib/Expectation.js:333:28)
      at Context.<anonymous> (test/indexTest.js:26:17)
      at process.processImmediate (node:internal/timers:471:21)

I am receiving this error code and none of the above suggestions have solved this problem. Any other suggestions?
